import * as fs from "fs/promises";
import * as path from "path";

export class MarkdownWriter {
  async write(
    aiDocsPath: string,
    fileName: string,
    title: string,
    repository: string,
    branch: string,
    body: string,
    outputFolder = "generated-docs",
    generatedBy = "Bank Spring Docs AI"
  ): Promise<string> {
    const targetDir = path.join(aiDocsPath, outputFolder);
    await fs.mkdir(targetDir, { recursive: true });
    const target = path.join(targetDir, fileName);
    const content = `# ${title}

Generated by ${generatedBy}

Repository: ${repository}
Branch: ${branch}
Generated at: ${new Date().toISOString()}

---

${body}
`;
    await fs.writeFile(target, content, "utf8");
    return target;
  }
}
